### ISSUE TITLE
LICENSE and CONTRIBUTORS.md from keras-retinanet

### ISSUE THREAD

**Issue by de-vri-es** [Nellaker-group/TowardsDeepPhenotyping#1]
Hey,

First of all, interesting project, and very cool that you decided to use `keras-retinanet` for it.

I noticed that you are distributing the `keras-retinanet` source with the `LICENSE` and `CONTRIBUTORS.md` files removed. This is not allowed by the Apache v2.0 license (or nearly any other open source license really).

In particular, section 4a and 4c of the license requires that the license, copyright notices and attribution notices are retained with any source distribution:
> 4a You must give any other recipients of the Work or Derivative Works a copy of this License; and
> ...
> 4c You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and
>...

Please keep this type of thing in mind when using open source software, and especially when redistributing it.

It would also be nice if you could link to the original repository[1] in your `README` so that other can easily find it, use it and contribute to it. This is not legally required, but it would be highly appreciated from our side :)

[1] https://github.com/fizyr/keras-retinanet

**Comment by GlastonburyC** [comment]
Hi,

The omission of the files you mentioned were not intentional, so we will happily add them to the project repository. We were very open about using your open source code, both raising an issue and acknowledging you in the paper, so we are happy to forfill the requests you have.

**Comment by de-vri-es** [comment]
Ah yes, I remember: https://github.com/fizyr/keras-retinanet/issues/363. We also like to see the code used of course. Especially in interesting projects like this ;)

No harm done, it's easy to forget about licensing requirements. Adding the two files I mentioned is enough for the legal requirements. And as mentioned, a link in the README would be nice as well.

Thank you for the quick response. Feel free to close the issue once the licensing issue is resolved ;)

**Comment by GlastonburyC** [comment]
I will be sure to add the link to the readme :) - thanks for the issue.

**Comment by hgaiser** [comment]
Don't mean to hijack this issue, but it also doesn't deserve a new issue ;)

I'm going to add this project to the README on keras-retinanet. It's nice to see all the projects people have used keras-retinanet for :)
